version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "[INFO] Setting environment variables"
  build:
    commands:
      - echo "[INFO] Building Spring Boot application"
      - mvn clean package
artifacts:
  files: target/*.jar
  name: app
  discard-paths: yes
